# Generated by Django 4.1.4 on 2022-12-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advocates',
            new_name='Advocate',
        ),
    ]
