# Generated by Django 4.1.4 on 2023-01-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_advocate_name_advocate_profile_pic_advocate_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
